import type { Project, Category } from './types'

export const sampleCategories: Category[] = [
  { _id: 'cat-1', title: 'Theaters', slug: { current: 'architecture-theatres' }, order: 1 },
  { _id: 'cat-2', title: 'Architectures', slug: { current: 'architecture-interieurs' }, order: 2 },
  { _id: 'cat-3', title: 'Expos', slug: { current: 'expositions' }, order: 3 },
  { _id: 'cat-4', title: 'Shows', slug: { current: 'defiles' }, order: 4 },
]

const placeholder = {
  _type: 'image' as const,
  asset: { _ref: '', _type: 'reference' as const },
}

export const sampleProjects: Project[] = [
  {
    _id: 'p-1',
    title: 'Figure Libre',
    slug: { current: 'figure-libre' },
    category: sampleCategories[2],
    year: 2024,
    location: 'Paris',
    country: 'France',
    venue: '19M',
    coverImage: placeholder,
    images: [],
    subtitle: '',
    credits: [],
    tags: [],
    order: 1,
    localCover: '/images/projects/figure-libre-1.jpg',
    localImages: [
      '/images/projects/figure-libre-1.jpg',
      '/images/projects/figure-libre-2.jpg',
      '/images/projects/figure-libre-3.jpg',
      '/images/projects/figure-libre-4.jpg',
      '/images/projects/axo.jpg',
    ],
  },
  {
    _id: 'p-2',
    title: 'The Wall',
    slug: { current: 'the-wall' },
    category: sampleCategories[0],
    year: 2024,
    location: 'Logroño',
    country: 'Spain',
    venue: 'CONCENTRICO',
    coverImage: placeholder,
    images: [],
    subtitle: '',
    credits: [],
    tags: [],
    order: 2,
    localCover: '/images/projects/the-wall.jpg',
    localImages: [
      '/images/projects/the-wall.jpg',
      '/images/projects/the-wall-2.jpg',
    ],
  },
  {
    _id: 'p-3',
    title: 'Culture Market',
    slug: { current: 'culture-market' },
    category: sampleCategories[2],
    year: 2024,
    location: 'Brussels',
    country: 'Belgium',
    venue: 'KANAL',
    coverImage: placeholder,
    images: [],
    subtitle: '',
    credits: [],
    tags: [],
    order: 3,
    localCover: '/images/projects/culture-market.jpg',
    localImages: [
      '/images/projects/culture-market.jpg',
    ],
  },
  {
    _id: 'p-4',
    title: 'Hermès FW25 Shanghai',
    slug: { current: 'hermes-fw25-shanghai' },
    category: sampleCategories[3],
    year: 2025,
    location: 'Shanghai',
    country: 'China',
    venue: 'Hermès',
    coverImage: placeholder,
    images: [],
    subtitle: '',
    credits: [],
    tags: [],
    order: 4,
    localCover: '/images/projects/hermes-1.jpg',
    localImages: [
      '/images/projects/hermes-1.jpg',
      '/images/projects/hermes-2.jpg',
    ],
  },
  {
    _id: 'p-5',
    title: 'Ball Theater',
    slug: { current: 'ball-theater' },
    category: sampleCategories[0],
    year: 2023,
    location: 'Paris',
    country: 'France',
    venue: '',
    coverImage: placeholder,
    images: [],
    subtitle: '',
    credits: [],
    tags: [],
    order: 5,
    localCover: '/images/projects/ball-theater.jpg',
    localImages: [
      '/images/projects/ball-theater.jpg',
    ],
  },
  {
    _id: 'p-6',
    title: 'Les Portes du possible',
    slug: { current: 'les-portes-du-possible' },
    category: sampleCategories[2],
    year: 2024,
    location: 'Paris',
    country: 'France',
    venue: '',
    coverImage: placeholder,
    images: [],
    subtitle: '',
    credits: [],
    tags: [],
    order: 6,
    localCover: '/images/projects/les-portes.jpg',
    localImages: [
      '/images/projects/les-portes.jpg',
      '/images/projects/crop.jpg',
    ],
  },
]
