import type { Project, Category } from './types'

export const sampleCategories: Category[] = [
  { _id: 'cat-1', title: 'Architecture [Théâtres]', slug: { current: 'architecture-theatres' }, order: 1 },
  { _id: 'cat-2', title: 'Architecture [Intérieurs]', slug: { current: 'architecture-interieurs' }, order: 2 },
  { _id: 'cat-3', title: 'Expositions', slug: { current: 'expositions' }, order: 3 },
  { _id: 'cat-4', title: 'Défilés', slug: { current: 'defiles' }, order: 4 },
  { _id: 'cat-5', title: 'Célébrations', slug: { current: 'celebrations' }, order: 5 },
  { _id: 'cat-6', title: 'Scénographie de théâtre', slug: { current: 'scenographie-theatre' }, order: 6 },
  { _id: 'cat-7', title: 'Showroom', slug: { current: 'showroom' }, order: 7 },
]

const placeholder = {
  _type: 'image' as const,
  asset: { _ref: '', _type: 'reference' as const },
}

export const sampleProjects: Project[] = [
  {
    _id: 'p-1',
    title: 'Figure Libre',
    slug: { current: 'figure-libre' },
    category: sampleCategories[2],
    year: 2024,
    location: 'Paris, France',
    country: 'FRANCE',
    venue: '19M',
    projectType: 'Exhibition Scenography',
    surface: '650m2',
    curator: 'Stéphane Ashpool, Méryl Laurent',
    description: 'Figure Libre invites visitors to discover how sportswear can be an art form, an approach that is not only technical—responding to the body\'s urgent need to move with ease in pursuit of performance—but also a visual celebration that honors the body through the choice of fabrics, textiles, and embellishments that celebrate prowess.',
    coverImage: placeholder,
    images: [],
    planImage: null,
    order: 1,
  },
  {
    _id: 'p-2',
    title: 'The Wall',
    slug: { current: 'the-wall' },
    category: sampleCategories[0],
    year: 2024,
    location: 'Logroño, Spain',
    country: 'SPAIN',
    venue: 'CONCENTRICO',
    projectType: 'Installation',
    surface: '',
    curator: '',
    description: '',
    coverImage: placeholder,
    images: [],
    planImage: null,
    order: 2,
  },
  {
    _id: 'p-3',
    title: 'Culture Market',
    slug: { current: 'culture-market' },
    category: sampleCategories[2],
    year: 2024,
    location: 'Brussels, Belgium',
    country: 'BELGIUM',
    venue: 'KANAL',
    projectType: 'Exhibition Scenography',
    surface: '',
    curator: '',
    description: '',
    coverImage: placeholder,
    images: [],
    planImage: null,
    order: 3,
  },
  {
    _id: 'p-4',
    title: 'Hermès FW25 Shanghai',
    slug: { current: 'hermes-fw25-shanghai' },
    category: sampleCategories[3],
    year: 2025,
    location: 'Shanghai, China',
    country: 'CHINA',
    venue: 'Hermès',
    projectType: 'Fashion Show',
    surface: '',
    curator: '',
    description: '',
    coverImage: placeholder,
    images: [],
    planImage: null,
    order: 4,
  },
  {
    _id: 'p-5',
    title: 'Ball Theater',
    slug: { current: 'ball-theater' },
    category: sampleCategories[0],
    year: 2023,
    location: 'Paris, France',
    country: 'FRANCE',
    venue: '',
    projectType: 'Architecture',
    surface: '',
    curator: '',
    description: '',
    coverImage: placeholder,
    images: [],
    planImage: null,
    order: 5,
  },
  {
    _id: 'p-6',
    title: 'Les Portes du possible',
    slug: { current: 'les-portes-du-possible' },
    category: sampleCategories[2],
    year: 2024,
    location: 'Paris, France',
    country: 'FRANCE',
    venue: '',
    projectType: 'Exhibition',
    surface: '',
    curator: '',
    description: '',
    coverImage: placeholder,
    images: [],
    planImage: null,
    order: 6,
  },
]
